---
# Component with both GitHub and Jira Scorecards
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: addon-test
  annotations:
    github.com/project-slug: janus-qe/overlay-scorecard-plugin-test
    backstage.io/source-location: url:https://github.com/janus-qe/overlay-scorecard-plugin-test
    jira/project-key: RHTAP
spec:
  type: service
  owner: user:test1
  lifecycle: production
