---
# Component with both GitHub and Jira Scorecards
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: all-scorecards
  annotations:
    github.com/project-slug: janus-qe/overlay-scorecard-plugin-test
    backstage.io/source-location: url:https://github.com/janus-qe/overlay-scorecard-plugin-test
    jira/project-key: RSPT
    openssf/scorecard-location: https://api.securityscorecards.dev/projects/github.com/ossf/scorecard
    scorecard.io/disabled-metrics: openssf.maintained
    github.com/dependabot: "false"
spec:
  type: service
  owner: user:test1
  lifecycle: production
