---
# Component with filecheck Scorecard only
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: filecheck-scorecard-github
  annotations:
    backstage.io/source-location: url:https://github.com/janus-qe/overlay-scorecard-plugin-test
spec:
  type: service
  owner: user:test1
  lifecycle: production
