---
# Component with Jira Scorecard only
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jira-scorecard-only
  annotations:
    jira/project-key: RSPT
    scorecard.io/disabled-metrics: filecheck.readme,filecheck.license
spec:
  type: service
  owner: user:test1
  lifecycle: production
