---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openssf-scorecard-only
  annotations:
    openssf/scorecard-location: https://api.securityscorecards.dev/projects/github.com/ossf/scorecard
    scorecard.io/disabled-metrics: openssf.maintained,filecheck.readme,filecheck.license
spec:
  type: service
  owner: group:development/guests
  lifecycle: experimental
